import { Space_Grotesk } from "next/font/google";
import NavBar from "@/components/header/nav-bar";
import Footer from "@/components/footer/footer";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>
        <NavBar />
        <main style={{ marginTop: "87px" }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
